name: Build Project Action
run-name: Building Project
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      steps:
        - name: Setup environment
          uses: actions/setup-go@v5.3.0
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Project check
          uses: securego/gosec@v2.22.1
