name: Code check
run-name: Project source code checking
on:
  pull_request:
    branches:
      - main
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-go@v5.3.0
      - name: Project check
        uses: securego/gosec@v2.22.1
        with:
          args: ./..
