name: Windows Build
on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed
jobs:
  linux-build:
    runs-on: windows-latest
    steps:
      - name: Checking out project
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-go@v5.3.0
      - name: Build the project
        run: make platform.windows
